# -*- coding: utf-8 -*-
"""CuadernoClase-DeterminacionOrbita-JorgeZuluaga.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LOQh0Md5x6vvRlHWh_ct8BqxnSZICY8i

# Cuaderno de clase
## Mecánica Celeste (2026-1) con Jorge I. Zuluaga
## Determinación de Órbita
"""

!pip install -Uq pymcel

import pymcel as pc
import numpy as np
import matplotlib.pyplot as plt
import spiceypy as spy

tabla, jd, X = pc.consulta_horizons(
    id='Apophis',
    location='@SSB',
    epochs='2026-04-20'
)
X

rvec = X[:3]
r = np.linalg.norm(rvec)
vvec = X[3:]
v = np.linalg.norm(vvec)
rvec, vvec

"""Para la determinación de los elementos orbitales necesito estos vectores: $\vec r, \vec v, \vec h, \vec e, \vec n$"""

# MARE
hvec = np.cross(rvec, vvec)
h = np.linalg.norm(hvec)

# Vector de Laplace
mu = pc.constantes.mu_sun  # Aproximacion que no me permiten en la UdeA pero lo voy a hacer..
evec = np.cross(vvec, hvec) / mu - rvec / r
e = np.linalg.norm(evec)

# Vector de nodos
nvec = np.cross([0,0,1], hvec)
n = np.linalg.norm(nvec)

hvec, evec , nvec, mu

"""Ahora a determinar los elementos orbitales $(p, e, I, \Omega, \omega, f)$"""

p = h**2 / mu
e = e # Es la magnitu de evec
I = np.arccos(hvec[2]/h)
rad = 180 / np.pi
I*rad

omegap = np.arccos(nvec@evec/(n*e))
omega = omegap if evec[2] > 0 else 2*np.pi - omegap
omega*rad

Omegap = np.arccos(nvec@[1,0,0]/n)
if nvec[1] > 0:
  Omega = Omegap
else:
  Omega = 2*np.pi - Omegap

Omega = Omegap if nvec[1] > 0 else 2*np.pi - Omegap

Omega*rad

fp = np.arccos(rvec@evec/(r*e))
f = fp if rvec@vvec/r > 0 else 2*np.pi - fp
f*rad

def calcular_elementos_orbitales(rvec, vvec, mu):
    r = np.linalg.norm(rvec)
    v = np.linalg.norm(vvec)

    # Momento angular
    hvec = np.cross(rvec, vvec)
    h = np.linalg.norm(hvec)

    # Vector de excentricidad (Laplace)
    evec = np.cross(vvec, hvec) / mu - rvec / r
    e = np.linalg.norm(evec)

    # Vector de nodos
    nvec = np.cross([0, 0, 1], hvec)
    n = np.linalg.norm(nvec)

    # Elementos orbitales
    p = h**2 / mu
    I = np.arccos(hvec[2] / h)

    # Ascensión recta del nodo ascendente (Omega)
    if n == 0:
        Omega = 0 # Órbita ecuatorial, nodo indefinido
    else:
        Omegap = np.arccos(np.dot(nvec, [1, 0, 0]) / n)
        if nvec[1] > 0:
            Omega = Omegap
        else:
            Omega = 2 * np.pi - Omegap

    # Argumento del periapsis (omega)
    if e == 0:
        omegap = 0 # Órbita circular, periapsis indefinida
    elif n == 0:
        omegap = np.arctan2(evec[1], evec[0]) # Órbita ecuatorial, nodo indefinido
    else:
        omegap = np.arccos(np.dot(nvec, evec) / (n * e))
        if evec[2] < 0:
            omegap = 2 * np.pi - omegap

    # Anomalía verdadera (f)
    fp = np.arccos(np.dot(rvec, evec) / (r * e))
    if np.dot(rvec, vvec) > 0:
        f = fp
    else:
        f = 2 * np.pi - fp

    return p, e, I, Omega, omegap, f

p, e, I, Omega, omega, f = calcular_elementos_orbitales(rvec, vvec, mu)
p, e, I*rad, Omega*rad, omega*rad, f*rad

"""## La órbita del Sol"""

tabla, jds, Xs = pc.consulta_spice(
    id='Sun',
    location='@SSB',
    epochs=dict(start='2026-04-20', stop='2058-04-20', step='180d')
)
Xs = np.array(Xs)

mu = pc.constantes.mu_sun + pc.constantes.mu_jupiter + pc.constantes.mu_saturn
Es = np.zeros((len(jds), 6))
for i, jd in enumerate(jds):
  rvec = Xs[i, :3]
  vvec = Xs[i, 3:]
  p, e, I, Omega, omega, f = calcular_elementos_orbitales(rvec, vvec, mu)
  hvec = np.cross(rvec, vvec)
  Es[i] = p, e, I, Omega, omega, f
  plt.plot(rvec[0], rvec[1], 'ko')

plt.axis('equal')
plt.grid()

plt.plot(jds, Es[:,0])

